### ISSUE TITLE
Add release pipeline

### ISSUE THREAD

**Issue by l50** [CowDogMoo/ansible-vnc-zsh#4]
Once we are ready to open source, we will need to create a release github action for galaxy:

Example taken from https://raw.githubusercontent.com/l50/ansible-sliver/main/.github/workflows/release.yml:

```yaml
---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: Release
on:
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: "l50.sliver"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "l50.sliver"

      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
```
